// Shared sample data for all four variants.
window.NEO = {
  projects: [
    { id:'p1', name:'みんなの通学路マップ', team:'チーム筑紫丘', lead:'田中 美咲', members:5, progress:78, status:'active', start:'2025-09-01', due:'2026-02-09', milestone:'実証実験準備', tasks:{done:34,total:48}, streak:14, badges:['MVP伴走','現場主義'], pl:+184000, risk:'low' },
    { id:'p2', name:'GO!GO!博多うどん部',  team:'うどん研究会', lead:'山口 蓮', members:6, progress:62, status:'active', start:'2025-10-01', due:'2026-03-15', milestone:'パートナー連携', tasks:{done:21,total:42}, streak:8, badges:['巻き込み力'], pl:-42000, risk:'mid' },
    { id:'p3', name:'高校生×伝統工芸 NEW LINE',  team:'NEW LINE', lead:'森本 千夏', members:4, progress:91, status:'active', start:'2025-08-15', due:'2026-02-09', milestone:'マッチデイ申請', tasks:{done:51,total:58}, streak:21, badges:['推進力','MVP伴走','楽しみ力'], pl:+312000, risk:'low' },
    { id:'p4', name:'糸島・空き家リノベ', team:'ITOSHIMA HOUSE', lead:'有村 颯', members:7, progress:44, status:'active', start:'2025-11-01', due:'2026-04-30', milestone:'プロトタイプ検証', tasks:{done:14,total:38}, streak:3, badges:[], pl:-128000, risk:'mid' },
    { id:'p5', name:'ZEPHYRファンクラブ高校生支部', team:'BLUE WAVE', lead:'金田 楓', members:9, progress:55, status:'active', start:'2025-09-20', due:'2026-02-09', milestone:'試合会場ブース', tasks:{done:18,total:34}, streak:11, badges:['チームワーク'], pl:+58000, risk:'low' },
    { id:'p6', name:'天神アンダーグラウンド・カフェ', team:'TENJIN UG', lead:'橋本 結', members:3, progress:28, status:'active', start:'2026-01-05', due:'2026-05-30', milestone:'コンセプト固め', tasks:{done:7,total:30}, streak:5, badges:[], pl:-24000, risk:'high' },
  ],
  themes: [
    { id:'t1', code:'NEO-001', sponsor:'ライジングゼファー福岡', title:'バスケを通じて地域を熱くする若者発の新文化', tag:'スポーツ×地域', status:'open', deadline:'2026-01-15', applicants:14, picked:8, prize:'実証実験@2/9' },
    { id:'t2', code:'NEO-002', sponsor:'西鉄バス',           title:'通学・通勤バスの“もう一つの価値”を再発明する', tag:'モビリティ', status:'open', deadline:'2026-02-01', applicants:9,  picked:3, prize:'路線実証' },
    { id:'t3', code:'NEO-003', sponsor:'やまや',             title:'伝統食×若者文化の新しい食卓体験', tag:'食×文化', status:'open', deadline:'2026-02-28', applicants:5,  picked:0, prize:'商品化検討' },
    { id:'t4', code:'NEO-004', sponsor:'福岡ソフトバンクホークス', title:'PayPayドームの空き時間を地域の遊び場に', tag:'スポーツ×地域', status:'draft', deadline:'—', applicants:0, picked:0, prize:'—' },
    { id:'t5', code:'NEO-005', sponsor:'九州電力',           title:'エネルギーを“自分ごと”にする中高生向け体験', tag:'エネルギー', status:'closed', deadline:'2025-11-30', applicants:22, picked:6, prize:'実施完了' },
  ],
  milestones: [
    { id:'m1', label:'チーム結成 & キックオフ',       date:'2025-09-05', done:true },
    { id:'m2', label:'実行計画 v1 提出',             date:'2025-10-20', done:true },
    { id:'m3', label:'プロトタイプ検証',             date:'2025-12-15', done:true },
    { id:'m4', label:'NEO基金 中間報告',             date:'2026-01-20', done:false, current:true },
    { id:'m5', label:'マッチデイ実証 @2/9',          date:'2026-02-09', done:false },
    { id:'m6', label:'完了報告 & 振り返り',           date:'2026-03-15', done:false },
  ],
  tasks: [
    { id:'k1', title:'高校生インタビュー × 5名',  owner:'美咲', due:'1/18', status:'doing', tag:'現場' },
    { id:'k2', title:'プレゼン資料 v3 ドラフト',  owner:'蓮',   due:'1/19', status:'doing', tag:'資料' },
    { id:'k3', title:'予算内訳 申請書反映',       owner:'颯',   due:'1/20', status:'review',tag:'申請' },
    { id:'k4', title:'会場レイアウト 図面',       owner:'千夏', due:'1/22', status:'todo',  tag:'現場' },
    { id:'k5', title:'SNS 告知文 3案',           owner:'結',   due:'1/24', status:'todo',  tag:'広報' },
    { id:'k6', title:'パートナー A社 アポ取り',   owner:'美咲', due:'1/16', status:'done',  tag:'連携' },
  ],
  events: [
    { d:'1/18', t:'14:00', label:'高校生インタビュー @ 筑紫丘高校', kind:'現場' },
    { d:'1/21', t:'19:30', label:'チーム定例 + 進捗共有',          kind:'定例' },
    { d:'1/24', t:'10:00', label:'NEO事務局 中間レビュー',         kind:'公式' },
    { d:'2/09', t:'13:00', label:'マッチデイ実証 @ 福岡市民体育館', kind:'本番' },
  ],
  // 14-criteria diagnosis radar
  radar: [
    { k:'目標設定', v:3, area:'skill', tip:'成功イメージを数値や状態で言語化できているか' },
    { k:'戦略力',   v:3, area:'skill', tip:'到達できる勝ち筋・シナリオを描けているか' },
    { k:'役割分担', v:2, area:'skill', tip:'誰が何を担うかが明確になっているか' },
    { k:'進捗管理', v:3, area:'skill', tip:'進捗が可視化され、遅れを早期に把握できているか' },
    { k:'チームワーク', v:3, area:'skill', tip:'互いを補完し合う関係性が築けているか' },
    { k:'決断力',   v:2, area:'skill', tip:'意思決定を先延ばしにせず重ねられているか' },
    { k:'推進力',   v:3, area:'skill', tip:'自律的にチームで物事を前に進められているか' },
    { k:'改善力',   v:2, area:'exec',  tip:'試行錯誤を通じて改善を繰り返せているか' },
    { k:'衝突力',   v:1, area:'exec',  tip:'違和感や反対意見を率直に伝え合えているか' },
    { k:'楽しみ力', v:3, area:'exec',  tip:'困難を成長機会と捉え、前向きに楽しめているか' },
    { k:'巻き込み力', v:3, area:'exec', tip:'企業・NEO・外部を巻き込めているか' },
    { k:'現場力',   v:3, area:'exec',  tip:'一次情報から学びを得られているか' },
    { k:'リスク管理', v:2, area:'exec', tip:'リスクや前提を洗い出し代替案を持てているか' },
    { k:'やり切り', v:2, area:'exec',  tip:'掲げた目標を最後まで責任を持って実行できているか' },
  ],
  proposals: [
    { id:'pr1', kind:'実行計画', summary:'Why の解像度を上げる：3つの社会課題を一つに絞り込み「地域の交通弱者の通学」へ', status:'pending' },
    { id:'pr2', kind:'WBS',     summary:'1月のタスクが多すぎ → 「インタビュー集中週」を作って5タスクを統合', status:'pending' },
    { id:'pr3', kind:'収支',    summary:'NEO基金から会場費10万を計上、自己資金は備品・印刷へ振り替え', status:'approved' },
    { id:'pr4', kind:'プロモ',  summary:'高校生インスタを起点に、保護者向けLINE公式を補助線として運用', status:'pending' },
  ],
  badges: [
    { k:'MVP伴走',   sub:'30日連続更新', icon:'★' },
    { k:'現場主義',   sub:'一次情報5回',  icon:'◎' },
    { k:'推進力',     sub:'14タスク完遂', icon:'▲' },
    { k:'楽しみ力',   sub:'振り返り×5',   icon:'♥' },
  ],
  framework: {
    'Why' : { title:'なぜやるのか', tip:'存在意義。誰のための、どの社会課題か。' },
    'Who' : { title:'誰に',         tip:'ペルソナ。具体的に一人を描けるくらい。' },
    'What': { title:'どんな提供価値', tip:'相手の人生にとっての価値。機能ではなく体験。' },
    'How' : { title:'どのように',    tip:'仕組み・座組み。継続できる構造。' },
  },
};
